### ISSUE TITLE
Can Haz Source Code?

### ISSUE THREAD

**Issue by ryaminal** [xxdesmus/canhazip.com#1]
Hi there,

Wondering if I'm missing something in this repo or if you decided to not publish the source code?

I'm assuming this is run in a cloudflare worker, but I don't know anything else about this service. We are using this service at the moment but didn't think about who was hosting this and other stuff.

Mostly want to make sure we aren't hitting this endpoint too hard or anything.

Thanks for building and hosting this for the world!

**Comment by xxdesmus** [comment]
Hi there,

The website is indeed powered by Cloudflare Workers. As such, there's no way to hit it too hard. :) I can publish the Worker code if you're particularly interested. Just let me know.

**Comment by nczz** [comment]
> Hi there,
> 
> The website is indeed powered by Cloudflare Workers. As such, there's no way to hit it too hard. :) I can publish the Worker code if you're particularly interested. Just let me know.

Hi @xxdesmus , I am really interested! Please publish! Thank you.

**Comment by xxdesmus** [comment]
@ryaminal and @nczz  Cloudflare Worker code added here: https://github.com/xxdesmus/canhazip.com/blob/master/cloudflare-worker.txt

**Comment by ryaminal** [comment]
awesome! thanks so much @xxdesmus.
